data:
  loader_kwargs:
    batch_size: 64
    bit_encoded_messages: false
    clip_history_days: false
    num_workers: 8
    preload: true
    relative_days: true
    shuffle: true
  paths:
    train:
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-0_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-1_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-2_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-3_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-4_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-5_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-6_20200509-182246-output.zip
    validate:
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-7_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-8_20200509-182246-output.zip
      - ./data/1k_app_1_v3/sim_v2_people-1000_days-30_init-0.003_seed-9_20200509-182246-output.zip
  transforms:
    train:
      kwargs:
        FractionalEncounterDurationNoise:
          fractional_noise: 0.01
        QuantizedGaussianMessageNoise:
          noise_std: 0.5
      names:
      - QuantizedGaussianMessageNoise
      - FractionalEncounterDurationNoise

losses:
  kwargs:
    contagion:
      allow_multiple_exposures: true
      diurnal_exposures: true
    infectiousness: {}
  weights:
    contagion: 0.7
    infectiousness: 1.0

metrics:
  kwargs:
    diurnal_exposures: true

model:
  name: MomentNet
  kwargs:
    capacity: 128
    encounter_output_features: 1
    latent_variable_output_features: 1
    message_dim: 1
    num_health_history_features: 28
    num_health_profile_features: 12
    block_types: l

optim:
  kwargs:
    eta_max: 0.0008
    eta_min: 8.0e-06
    num_steps: 100000
    num_warmup_steps: 5000
    weight_decay: 1.0e-05
  name: WarmCosineAdam

tensorboard:
  log_scalars_every: 10

training:
  checkpoint:
    every: 2
    if_best: true
  num_epochs: 40

wandb:
  log_every: 50
  use: true
