data:
  paths:
    train:
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-0_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-1_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-2_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-3_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-4_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-5_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-6_20200430-012202-output.zip"
    validate:
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-7_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-8_20200430-012202-output.zip"
      - "./data/1k_app_0.5/sim_v2_people-1000_days-60_init-0.01_seed-9_20200430-012202-output.zip"
  loader_kwargs:
    batch_size: 64
    shuffle: true
    num_workers: 8      # Set this to match the resources you have available
    relative_days: true
    clip_history_days: false
    preload: true      # Set this to true if you have 16GB+ of RAM

model:
  name: MixSetNet
  kwargs:
    capacity: 128
    dropout: 0.1
    encounter_duration_embedding_dim: 32
    encounter_duration_embedding_mode: sines
    encounter_duration_num_thermo_bins: 32
    encounter_duration_thermo_range:
      - 0.0
      - 6.0
    encounter_output_features: 1
    encounter_partner_id_embedding_dim: 32
    health_history_embedding_dim: 64
    health_profile_embedding_dim: 32
    latent_variable_output_features: 1
    message_dim: 1
    message_embedding_dim: 128
    num_encounter_partner_id_bits: 16
    num_heads: 4
    num_health_history_features: 29
    num_health_profile_features: 12
    block_capacity: 128
    block_types: rrrsr
    srb_aggregation: max
    srb_feature_size_divisor: 1
    time_embedding_dim: 32
    use_encounter_partner_id_embedding: false
    use_learned_time_embedding: true

losses:
  kwargs:
    infectiousness: {}
    contagion:
      allow_multiple_exposures: true
  weights:
    infectiousness: 1.
    contagion: 1.

optim:
  name: "WarmCosineAdam"
  kwargs:
    num_steps: 100000
    num_warmup_steps: 5000
    eta_min: 0.000008
    eta_max: 0.0008

training:
  num_epochs: 40
  checkpoint:
    every: 5
    if_best: true
    save_trace: true

wandb:
  use: false
  log_every: 50

tensorboard:
  log_scalars_every: 10