device: "cpu"

data:
  paths:
    train: "./data/0-risks"
    validate: "./data/1-risks"
  loader_kwargs:
    batch_size: 8
    shuffle: true
    num_workers: 1
    relative_days: true

model:
  kwargs:
    capacity: 128
    dropout: 0.1
    num_health_features: 13
    health_embedding_dim: 64
    time_embedding_dim: 32
    num_encounter_partner_id_bits: 16
    encounter_partner_id_embedding_dim: 32
    message_dim: 8
    message_embedding_dim: 32
    num_heads: 4
    sab_capacity: 128
    num_sabs: 2
    pool_latent_entities: false
    use_logit_sink: false
    encounter_output_features: 1
    latent_variable_output_features: 1

losses:
  kwargs:
    infectiousness: {}
    contagion:
      allow_multiple_exposures: true
  weights:
    infectiousness: 1.
    contagion: 1.

optim:
  kwargs:
    lr: 0.0001

training:
  num_epochs: 10

wandb:
  log_every: 50
