data:
  paths:
    train:
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-0_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-1_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-2_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-3_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-4_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-5_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-6_20200429-143659-output.zip"
    validate:
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-7_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-8_20200429-143659-output.zip"
      - "./data/4-29-1k-final/sim_v2_people-1000_days-60_init-0.01_seed-9_20200429-143659-output.zip"
  loader_kwargs:
    batch_size: 64
    shuffle: true
    num_workers: 8      # Set this to match the resources you have available
    relative_days: true
    clip_history_days: false
    preload: false      # Set this to true if you have massive RAM

model:
  kwargs:
    capacity: 128
    dropout: 0.1
    num_health_history_features: 13
    health_history_embedding_dim: 64
    num_health_profile_features: 7
    health_profile_embedding_dim: 32
    use_learned_time_embedding: true
    time_embedding_dim: 32
    encounter_duration_embedding_dim: 32
    encounter_duration_embedding_mode: "sines"    # Options: {"sines", "thermo"}
    encounter_duration_thermo_range: [0.0, 6.0]
    encounter_duration_num_thermo_bins: 32
    num_encounter_partner_id_bits: 16
    use_encounter_partner_id_embedding: false
    encounter_partner_id_embedding_dim: 32
    message_dim: 8
    message_embedding_dim: 128
    num_heads: 4
    sab_capacity: 128
    num_sabs: 2
    encounter_output_features: 1
    latent_variable_output_features: 1

losses:
  kwargs:
    infectiousness: {}
    contagion:
      allow_multiple_exposures: true
  weights:
    infectiousness: 1.
    contagion: 1.

optim:
  name: "WarmCosineAdam"
  kwargs:
    num_steps: 100000
    num_warmup_steps: 5000
    eta_min: 0.000008
    eta_max: 0.0008

training:
  num_epochs: 40
  checkpoint:
    every: 5
    if_best: true

wandb:
  use: false
  log_every: 50

tensorboard:
  log_scalars_every: 10