data:
  paths:
    train: "./data/1k-1-output"
    validate: "./data/1k-1-output"
  loader_kwargs:
    batch_size: 8
    shuffle: true
    num_workers: 1
    relative_days: true

model:
  kwargs:
    capacity: 128
    dropout: 0.1
    num_health_history_features: 13
    health_history_embedding_dim: 32
    num_health_profile_features: 14
    health_profile_embedding_dim: 32
    encounter_duration_embedding_mode: "thermo"
    encounter_duration_thermo_range: [0.0, 6.0]
    encounter_duration_num_thermo_bins: 32
    time_embedding_dim: 32
    encounter_duration_embedding_dim: 32
    num_encounter_partner_id_bits: 16
    encounter_partner_id_embedding_dim: 32
    message_dim: 8
    message_embedding_dim: 32
    num_heads: 4
    sab_capacity: 128
    num_sabs: 2
    encounter_output_features: 1
    latent_variable_output_features: 1

losses:
  kwargs:
    infectiousness: {}
    contagion:
      allow_multiple_exposures: true
  weights:
    infectiousness: 1.
    contagion: 1.

optim:
  name: "WarmCosineAdam"
  kwargs:
    num_steps: 100000
    num_warmup_steps: 5000
    eta_min: 0.00001
    eta_max: 0.0008

training:
  num_epochs: 40
  checkpoint:
    every: 5
    if_best: true

wandb:
  use: true
  log_every: 50

tensorboard:
  log_scalars_every: 10